name: New PR trigger test
on: [push, pull_request]

jobs:
  run_on_pr_create:
    runs-on: ubuntu-latest
    steps:
      - name: Run code on pull request creation
        run: |
          echo "Will add code checks here in the next challenge"
