name: Development and production workloads

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Experiment
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/experiment_job.yml -g mslearn-mlops -w aml-jobs

  production:
    name: Production
    runs-on: ubuntu-latest
    environment: production
    needs: experiment
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/production_job.yml -g mslearn-mlops -w aml-jobs --stream
